apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prom-replay.fullname" . }}-grafana-plugins
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
data:
  plugins.yaml: |-
    apiVersion: 1
    apps:
      - type: yesoreyeram-infinity-datasource
        org_id: 1
        disabled: false
