apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-replay.fullname" . }}-grafana
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "prom-replay.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
