apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prom-replay.fullname" . }}-grafana
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.grafana.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
