apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prom-replay.fullname" . }}-grafana-datasource
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        url: {{ include "prom-replay.vmURL" . }}
        access: proxy
        isDefault: true
      - name: ReplayManager
        type: yesoreyeram-infinity-datasource
        url: http://{{ include "prom-replay.fullname" . }}-replay-manager:8080
        access: proxy
        jsonData:
          global_queries: []
