apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-replay.fullname" . }}-minio
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9001
      targetPort: console
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/name: {{ include "prom-replay.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: minio
