apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prom-replay.fullname" . }}-minio
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
