apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prom-replay.fullname" . }}-minio
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
data:
  rootUser: {{ .Values.minio.rootUser | b64enc }}
  rootPassword: {{ .Values.minio.rootPassword | b64enc }}
