{{- if .Values.victoriametrics.enableRBAC }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: victoriametrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: victoriametrics
rules:
  - apiGroups: [""]
    resources: [nodes, pods, services, endpoints]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [nodes/proxy, nodes/metrics]
    verbs: [get]
  - nonResourceURLs: [/metrics]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: victoriametrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
subjects:
  - kind: ServiceAccount
    name: {{ include "prom-replay.fullname" . }}-victoriametrics
    namespace: {{ .Release.Namespace }}
{{- end }}
