{{- if .Values.victoriametrics.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prom-replay.victoriametrics.serviceAccountName" . }}
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: victoriametrics
  {{- with .Values.victoriametrics.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.victoriametrics.scrapeConfig }}
{{- if .Values.victoriametrics.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: victoriametrics
rules:
  - apiGroups: [""]
    resources: [nodes, pods, services, endpoints]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [nodes/proxy, nodes/metrics]
    verbs: [get]
  - nonResourceURLs: [/metrics]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: victoriametrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
subjects:
  - kind: ServiceAccount
    name: {{ include "prom-replay.victoriametrics.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: victoriametrics
rules:
  - apiGroups: [""]
    resources: [pods, services, endpoints]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
  labels:
    {{- include "prom-replay.labels" . | nindent 4 }}
    app.kubernetes.io/component: victoriametrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prom-replay.fullname" . }}-victoriametrics
subjects:
  - kind: ServiceAccount
    name: {{ include "prom-replay.victoriametrics.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
